name: burger-app

services:
  db:
    image: mysql:8.0
    container_name: db-1
    environment:
      MYSQL_DATABASE: burgerdb
      MYSQL_ROOT_PASSWORD: pasword12
    volumes:
      - burger_mysql_data:/var/lib/mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-ppasword12"]
      interval: 5s
      timeout: 3s
      retries: 30

  app:
    build: .
    image: burger-app
    container_name: app-1
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      # application.yml'de localhost yazdığı için docker içinde override şart:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/burgerdb?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: pasword12
      SPRING_SQL_INIT_MODE: always
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate

volumes:
  burger_mysql_data: